<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_DT" Id="{1257b383-7ca1-488c-a3a4-edeed7eb95f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_DT : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_DT(in);
TryConvert_DATE_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>