<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_DWORD" Id="{0e6a2de9-444f-4530-a59d-b98db8f3fc11}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_DWORD : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_DWORD(in);
TryConvert_DATE_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>