<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_REAL" Id="{02c95f9e-8d6c-41d0-b1c6-7e1c4554fc46}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_REAL : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_REAL(in);
TryConvert_DATE_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>