<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_LWORD" Id="{33dae9f0-2332-45a4-92fc-35278d514ce1}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_LWORD : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DATE_TO_LWORD(in);
TryConvert_DATE_TO_LWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
