<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_BOOL" Id="{dead2077-efca-42f9-829a-fbd4eaac02cc}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_BOOL : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DATE_TO_BOOL(in);
TryConvert_DATE_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
