<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_UDINT" Id="{8249c37d-541c-4006-9132-5f1015f05aa0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_UDINT : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_UDINT(in);
TryConvert_DATE_TO_UDINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>