<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_REAL_TO_REAL" Id="{d380db51-4993-4097-bc38-b5325fec6372}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_REAL_TO_REAL : BOOL
VAR_INPUT
	in : REAL;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_REAL_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>