<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_REAL_TO_BOOL" Id="{7178eca4-db37-45bb-846e-2a926b94a1ee}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_REAL_TO_BOOL : BOOL
VAR_INPUT
	in : REAL;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := REAL_TO_BOOL(in);
TryConvert_REAL_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
