<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_TOD_TO_TOD" Id="{57b8d073-198f-44a4-ba8c-7081180711eb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_TOD_TO_TOD : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_TOD_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>