<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_BOOL" Id="{8783d0bb-1fcb-439a-b6b1-104f122dfddc}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_BOOL : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := TOD_TO_BOOL(in);
TryConvert_TOD_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
