<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_DT" Id="{388b4d92-a34f-4112-8aa5-12cf37611ade}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_DT : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := TOD_TO_DT(in);
TryConvert_TOD_TO_DT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
