<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_DINT" Id="{47916d6f-ed52-46db-b441-b5231436e34e}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_DINT : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := TOD_TO_DINT(in);
TryConvert_TOD_TO_DINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
