<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_ULINT" Id="{fa11bfc5-89be-404d-b7f5-e5a39890c0b7}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_ULINT : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := TOD_TO_ULINT(in);
TryConvert_TOD_TO_ULINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
