<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_UINT_TO_UINT" Id="{694d9d10-1739-45b5-ad74-972948266481}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_UINT_TO_UINT : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_UINT_TO_UINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>