<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_STRING" Id="{ad775777-bf08-4501-86b5-d581acb59a4e}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_STRING : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UINT_TO_STRING(in);
TryConvert_UINT_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
