<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_BOOL" Id="{788daa0f-3ecc-4a00-8763-500c3a61c2c4}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_BOOL : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UINT_TO_BOOL(in);
TryConvert_UINT_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
