<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_DATE" Id="{34262b29-30bd-47ff-b16c-00a1f4e68ca3}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_DATE : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UINT_TO_DATE(in);
TryConvert_UINT_TO_DATE := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
