<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_LWORD" Id="{a840f4fc-112f-4b8d-8dd0-836b68a81840}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_LWORD : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UINT_TO_LWORD(in);
TryConvert_UINT_TO_LWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
