<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_ULINT" Id="{5ce88f7c-072e-4fce-a1f1-5e61020a0548}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_ULINT : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UINT_TO_ULINT(in);
TryConvert_UINT_TO_ULINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
