<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_TIME" Id="{8f253f0e-24c5-489f-9235-e6a196e78fe0}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_TIME : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO TIME;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UINT_TO_TIME(in);
TryConvert_UINT_TO_TIME := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
