<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_BOOL_TO_WORD" Id="{40421e94-96a2-47a4-ab2b-fa36addcf979}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_BOOL_TO_WORD : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_WORD(in);
Convert_BOOL_TO_WORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>