<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_BOOL_TO_DWORD" Id="{261656c6-8703-46bd-9d6c-d8d068d073ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_BOOL_TO_DWORD : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_DWORD(in);
Convert_BOOL_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>