<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_BOOL_TO_TOD" Id="{b06bcdb1-eb8e-4cb6-979f-e7da05ae2778}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_BOOL_TO_TOD : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_TOD(in);
Convert_BOOL_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>