<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_TOD" Id="{e2b76cbb-54b3-4143-8b1f-5c1913e4382c}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_TOD : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := BOOL_TO_TOD(in);
TryConvert_BOOL_TO_TOD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
