<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_LWORD" Id="{9cf55fc5-b6d1-4a16-a559-ac98c73a8663}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_LWORD : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_LWORD(in);
TryConvert_BOOL_TO_LWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>