<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_BYTE" Id="{64563b63-f711-4b59-a926-4ff42225720c}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_BYTE : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO BYTE;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := BOOL_TO_BYTE(in);
TryConvert_BOOL_TO_BYTE := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
