<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_BOOL" Id="{10249f75-2adb-4f23-a23f-7b2c7da3f975}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_BOOL : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_BOOL_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
