<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_USINT" Id="{3cb15360-576e-4d46-8d33-2da2b92652a0}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_USINT : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO USINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := BOOL_TO_USINT(in);
TryConvert_BOOL_TO_USINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
