<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_BYTE" Id="{762cdd17-f0e7-4943-8e90-62098b60f635}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_BYTE : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_BYTE(in);
TryConvert_BOOL_TO_BYTE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>