<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_USINT_TO_USINT" Id="{61f98346-e01c-4f8f-b8de-bd29fe212bbb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_USINT_TO_USINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_USINT_TO_USINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>