<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_LREAL" Id="{a9311bb3-8435-44c0-8b20-76f8505405c2}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_LREAL : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := USINT_TO_LREAL(in);
TryConvert_USINT_TO_LREAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
