<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_UINT" Id="{6ed15de1-23dd-4723-9ce6-d2601d99591e}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_UINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := USINT_TO_UINT(in);
TryConvert_USINT_TO_UINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
