<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_INT" Id="{a40b29c2-a88c-44cb-97a9-bc78543abc87}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_INT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO INT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := USINT_TO_INT(in);
TryConvert_USINT_TO_INT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
