<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_BOOL" Id="{7ea4887c-9ba7-46c1-a4c3-a1db4d46dcbe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_BOOL : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_BOOL(in);
TryConvert_USINT_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>