<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_DWORD" Id="{62a1b683-6a11-45bc-9386-e47765d8e24f}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_DWORD : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := USINT_TO_DWORD(in);
TryConvert_USINT_TO_DWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
