<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_USINT" Id="{4d216b35-4621-4cfa-8099-311ff1fe9b1c}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_USINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO USINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_USINT_TO_USINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
