<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_UDINT" Id="{c5807844-547d-4b67-991a-d2307f9f8062}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_UDINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := USINT_TO_UDINT(in);
TryConvert_USINT_TO_UDINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
