<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_BOOL" Id="{108e3e54-532a-4ee8-b5d8-2f4ca6825a23}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_BOOL : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := USINT_TO_BOOL(in);
TryConvert_USINT_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
