<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DINT_TO_BOOL" Id="{7d90bfe3-4711-4f94-8aff-7b2ba01bf39c}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DINT_TO_BOOL : BOOL
VAR_INPUT
	in : DINT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DINT_TO_BOOL(in);
TryConvert_DINT_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
