<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DINT_TO_LREAL" Id="{973e8c29-a6f6-4cc2-8c25-1aea91a24dc4}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DINT_TO_LREAL : BOOL
VAR_INPUT
	in : DINT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DINT_TO_LREAL(in);
TryConvert_DINT_TO_LREAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
