<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DINT_TO_STRING" Id="{bcf1e215-4387-4906-9ba7-0727fa6126c6}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DINT_TO_STRING : BOOL
VAR_INPUT
	in : DINT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DINT_TO_STRING(in);
TryConvert_DINT_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
