<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_LINT_TO_LINT" Id="{17910784-5ef5-4d1c-a3dd-831ccfeca1fc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_LINT_TO_LINT : BOOL
VAR_INPUT
	in : LINT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_LINT_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>