<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LINT_TO_LINT" Id="{2c6009eb-3a8d-4045-80c1-f8e091f9d9ba}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LINT_TO_LINT : BOOL
VAR_INPUT
	in : LINT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_LINT_TO_LINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
