<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LINT_TO_BOOL" Id="{a694a57f-a722-4385-ba2c-e74671ca747a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_LINT_TO_BOOL : BOOL
VAR_INPUT
	in : LINT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := LINT_TO_BOOL(in);
TryConvert_LINT_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>