<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LINT_TO_REAL" Id="{668be3b1-4437-4e05-99de-695b01ce54ac}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LINT_TO_REAL : BOOL
VAR_INPUT
	in : LINT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := LINT_TO_REAL(in);
TryConvert_LINT_TO_REAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
