<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LINT_TO_BOOL" Id="{deb86616-54fa-4ed4-817f-ea62946600f1}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LINT_TO_BOOL : BOOL
VAR_INPUT
	in : LINT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := LINT_TO_BOOL(in);
TryConvert_LINT_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
