<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_INT_TO_REAL" Id="{68832591-ba3a-4b36-92c3-f4c934a6539b}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_INT_TO_REAL : BOOL
VAR_INPUT
	in : INT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := INT_TO_REAL(in);
TryConvert_INT_TO_REAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
