<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_SINT_TO_SINT" Id="{64a08a87-ed07-4aa4-96cf-5a4fdae7f6ac}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_SINT_TO_SINT : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO SINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_SINT_TO_SINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>