<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_SINT_TO_LINT" Id="{d78ec892-1ab7-42e7-9cd1-96a5f80da258}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_SINT_TO_LINT : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := SINT_TO_LINT(in);
TryConvert_SINT_TO_LINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
