<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_SINT_TO_DINT" Id="{abe7754a-2170-432d-97fb-1b7edb657613}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_SINT_TO_DINT : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := SINT_TO_DINT(in);
TryConvert_SINT_TO_DINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
