<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_SINT_TO_STRING" Id="{83caac5b-6c70-47ef-83e6-1e838800c2c3}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_SINT_TO_STRING : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := SINT_TO_STRING(in);
TryConvert_SINT_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
