<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_BYTE_TO_BYTE" Id="{bcb76aec-8846-4f87-aa24-3fcad9130ecc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_BYTE_TO_BYTE : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_BYTE_TO_BYTE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>