<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_LINT" Id="{3c247105-3158-42fd-ab72-c67c52859388}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_LINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := BYTE_TO_LINT(in);
TryConvert_BYTE_TO_LINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
