<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_DATE" Id="{c536b3d3-3d05-45cb-8b89-9bdf2a15d249}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_DATE : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_DATE(in);
TryConvert_BYTE_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>