<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_DWORD" Id="{be9ae90c-1a4d-4dc3-a6f1-db6f2fe3ec29}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_DWORD : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_DWORD(in);
TryConvert_BYTE_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>