<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_UDINT" Id="{b5357d5c-55e3-43ab-865f-a4f06a425048}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_UDINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_UDINT(in);
TryConvert_BYTE_TO_UDINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>