<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_LINT" Id="{e5e70ecc-4f28-4f02-8d93-d6262f2653a8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_LINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_LINT(in);
TryConvert_BYTE_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>