<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_INT" Id="{2281d910-130d-4125-853e-37ebf1aa65c4}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_INT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO INT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := BYTE_TO_INT(in);
TryConvert_BYTE_TO_INT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
