<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_BOOL" Id="{cc576545-2d80-46ce-82cd-81e6956dd240}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_BOOL : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_BOOL(in);
TryConvert_BYTE_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>