<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_LREAL" Id="{dfd52143-92cf-40b4-a76c-26bceea3a282}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_LREAL : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_LREAL(in);
TryConvert_BYTE_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>