<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_BYTE" Id="{82c04ac5-c95a-402c-adba-ec3c95e75c88}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_BYTE : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO BYTE;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_BYTE_TO_BYTE := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
