<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_STRING" Id="{076831f6-bf2f-4969-9bfd-2f3b7838f518}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_STRING : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_STRING(in);
TryConvert_BYTE_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>