<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_TOD" Id="{577d26d9-f446-4d29-92c0-86ba9fe71817}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_TOD : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_TOD(in);
TryConvert_BYTE_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>