<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_USINT" Id="{db610eed-ccbd-4d2e-a8c6-fe205d6e5b23}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_USINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_USINT(in);
TryConvert_BYTE_TO_USINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>