<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_UDINT" Id="{8451f273-4837-4a30-a333-6ab59fe17e55}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_UDINT : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DT_TO_UDINT(in);
TryConvert_DT_TO_UDINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
