<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_ULINT" Id="{d78d136b-adaa-40c9-8ac2-59c00246619f}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_ULINT : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DT_TO_ULINT(in);
TryConvert_DT_TO_ULINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
