<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_DT" Id="{cbed759d-07b9-4fac-a42c-7e75e9f08d17}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_DT : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_DT_TO_DT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
