<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_BOOL" Id="{05bed8af-7b4a-4be0-8a7c-e0205ca0fac1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_BOOL : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DT_TO_BOOL(in);
TryConvert_DT_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>