<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_DT" Id="{c252d7fe-e597-48d5-9bcd-6abb433f9cb9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_DT : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_DT_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>