<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_STRING" Id="{3adb45cb-dec5-4887-8e23-51cf32ef692e}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_STRING : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DT_TO_STRING(in);
TryConvert_DT_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
