<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_DWORD" Id="{53324ed0-5383-4618-b5c2-bc686c390164}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_DWORD : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DT_TO_DWORD(in);
TryConvert_DT_TO_DWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
