<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_BOOL" Id="{d075efc8-805d-48c9-b52e-8858d29191e9}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_BOOL : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DT_TO_BOOL(in);
TryConvert_DT_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
