<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_LREAL" Id="{5ef9d815-baa5-40b1-b82b-a28ffaf86f51}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_LREAL : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DT_TO_LREAL(in);
TryConvert_DT_TO_LREAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
