<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_TIME_TO_TIME" Id="{b2aec6ed-20bf-469c-a299-c00f73d6d478}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_TIME_TO_TIME : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO TIME;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_TIME_TO_TIME := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>