<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TIME_TO_DWORD" Id="{94c22ce4-8531-4a01-b852-ae5cb3a00026}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_TIME_TO_DWORD : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := TIME_TO_DWORD(in);
TryConvert_TIME_TO_DWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
