<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_UINT" Id="{87d5fd9e-6055-4e7f-a103-e24a731195b3}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_UINT : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := WORD_TO_UINT(in);
TryConvert_WORD_TO_UINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
