<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_ULINT" Id="{8227b955-4303-4817-a77c-74e2fdc199a6}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_ULINT : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := WORD_TO_ULINT(in);
TryConvert_WORD_TO_ULINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
