<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_TIME" Id="{e628fe47-0e12-46e9-a663-6a33aea142bc}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_TIME : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO TIME;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := WORD_TO_TIME(in);
TryConvert_WORD_TO_TIME := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
