<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_WORD" Id="{5ae92396-4a21-4c22-81b2-4bfa3004f351}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_WORD : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_WORD_TO_WORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>