<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_STRING" Id="{67fbd5db-5712-4f40-b702-b033e3c25ff7}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_STRING : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := WORD_TO_STRING(in);
TryConvert_WORD_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
