<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_WORD" Id="{aca3493a-41d6-4625-90db-8e7ed97ba389}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_WORD : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO WORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_WORD_TO_WORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
