<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_LREAL" Id="{0364d126-715e-4574-a3b1-6b45fd95a2c1}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_LREAL : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := WORD_TO_LREAL(in);
TryConvert_WORD_TO_LREAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
