<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_TOD" Id="{a8a2d1b5-21cc-44f6-84f2-a6fe3bcb7d05}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_TOD : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := WORD_TO_TOD(in);
TryConvert_WORD_TO_TOD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
