<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_BOOL" Id="{9a6389ce-b122-4924-8832-03210afe1c03}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_BOOL : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_BOOL(in);
TryConvert_WORD_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>