<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_ULINT_TO_ULINT" Id="{be868e5a-7346-459c-9e26-a0f2fe787fb6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_ULINT_TO_ULINT : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
Convert_ULINT_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>