<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_STRING" Id="{e050aa73-40ad-4346-b67c-e5f5256da15a}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_STRING : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := ULINT_TO_STRING(in);
TryConvert_ULINT_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
