<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_LWORD" Id="{2f51f36d-9088-42f0-a734-524fc4797179}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_LWORD : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := ULINT_TO_LWORD(in);
TryConvert_ULINT_TO_LWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
