<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_ULINT" Id="{f9bd3403-2c09-4653-8f41-7a5bb1eeca29}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_ULINT : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_ULINT_TO_ULINT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
