<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7c22aba4-4a89-069c-18cd-1d4a5752fff2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	converters_TestSuit : Converters_TestSuit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>