<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LREAL_TO_LREAL" Id="{9b39c0dc-9db2-4be3-b785-83f56fbb9881}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LREAL_TO_LREAL : BOOL
VAR_INPUT
	in : LREAL;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_LREAL_TO_LREAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
