<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LREAL_TO_BOOL" Id="{8f0a0880-9858-4f5a-a389-a8e531756790}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LREAL_TO_BOOL : BOOL
VAR_INPUT
	in : LREAL;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := LREAL_TO_BOOL(in);
TryConvert_LREAL_TO_BOOL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
