<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_DT" Id="{9a9fab4d-fc7c-41de-a31e-22e408f15bbf}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_DT : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DWORD_TO_DT(in);
TryConvert_DWORD_TO_DT := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
