<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_LWORD" Id="{be646521-b907-489e-b638-dddcffc15525}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_LWORD : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DWORD_TO_LWORD(in);
TryConvert_DWORD_TO_LWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
