<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_BOOL" Id="{6c372ccb-4286-42a7-a5d2-7eef9db59b7a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_BOOL : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DWORD_TO_BOOL(in);
TryConvert_DWORD_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>