<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_STRING" Id="{e92b1172-1ec5-493e-b474-d376649f1bdf}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_STRING : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := DWORD_TO_STRING(in);
TryConvert_DWORD_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
