<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UDINT_TO_REAL" Id="{1c26be60-a749-49ad-91d2-b97da079781f}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_UDINT_TO_REAL : BOOL
VAR_INPUT
	in : UDINT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := UDINT_TO_REAL(in);
TryConvert_UDINT_TO_REAL := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
