<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LWORD_TO_LWORD" Id="{16ea3bb2-e7aa-4a71-bf98-51b0954632fd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_LWORD_TO_LWORD : BOOL
VAR_INPUT
	in : LWORD;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_LWORD_TO_LWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>