<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LWORD_TO_LWORD" Id="{0f45b8df-d9f2-420b-aebb-3e371d1f1aeb}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LWORD_TO_LWORD : BOOL
VAR_INPUT
	in : LWORD;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := in;
TryConvert_LWORD_TO_LWORD := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
