<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LWORD_TO_STRING" Id="{a6824783-19f1-4e22-bc49-334d047392e2}" SpecialFunc="None">
      <Declaration><![CDATA[FUNCTION TryConvert_LWORD_TO_STRING : BOOL
VAR_INPUT
	in : LWORD;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
      <Implementation>
          <ST><![CDATA[out := LWORD_TO_STRING(in);
TryConvert_LWORD_TO_STRING := TRUE;]]></ST>
      </Implementation>
      
  </POU>
</TcPlcObject>
